<a href="https://colab.research.google.com/github/nabilaaryanti/Aljabar_Linear/blob/main/Aplikasi_Ruang_Vektor_untuk_Deteksi_Plagiarism.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! git clone https://github.com/nabilaaryanti/Aljabar_Linear.git

fatal: destination path 'Aljabar_Linear' already exists and is not an empty directory.


In [2]:
import os
from numpy import vectorize 
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
os.chdir("/content/Aljabar_Linear/Data")

In [4]:
sample_files = [doc for doc in os.listdir() if doc.endswith('.txt')]
sample_files

['doc2.txt', 'doc3.txt', 'doc1.txt']

In [5]:
open('doc1.txt').read()

'Saya tidak suka makan buah mangga\n'

In [6]:
sample_contents = [open(File).read() for File in sample_files]
sample_contents

['Saya hanya suka makan buah nanas\n',
 'Saya tidak suka makan buah apapun',
 'Saya tidak suka makan buah mangga\n']

In [7]:
vectorize = lambda Text: TfidfVectorizer().fit_transform(Text).toarray()
vectorize

<function __main__.<lambda>>

In [8]:
similarity = lambda doc1, doc2: cosine_similarity([doc1, doc2])
similarity

<function __main__.<lambda>>

In [9]:
vectors = vectorize(sample_contents)
vectors

array([[0.        , 0.32052772, 0.54270061, 0.32052772, 0.        ,
        0.54270061, 0.32052772, 0.32052772, 0.        ],
       [0.57989687, 0.34249643, 0.        , 0.34249643, 0.        ,
        0.        , 0.34249643, 0.34249643, 0.44102652],
       [0.        , 0.34249643, 0.        , 0.34249643, 0.57989687,
        0.        , 0.34249643, 0.34249643, 0.44102652]])

In [10]:
s_vectors = list(zip(sample_files, vectors))
s_vectors

[('doc2.txt',
  array([0.        , 0.32052772, 0.54270061, 0.32052772, 0.        ,
         0.54270061, 0.32052772, 0.32052772, 0.        ])),
 ('doc3.txt',
  array([0.57989687, 0.34249643, 0.        , 0.34249643, 0.        ,
         0.        , 0.34249643, 0.34249643, 0.44102652])),
 ('doc1.txt',
  array([0.        , 0.34249643, 0.        , 0.34249643, 0.57989687,
         0.        , 0.34249643, 0.34249643, 0.44102652]))]

In [11]:
def check_plagiarism():
    results = set()
    global s_vectors
    for sample_a, text_vector_a in s_vectors:
        new_vectors = s_vectors.copy()
        current_index = new_vectors.index((sample_a, text_vector_a))
        del new_vectors[current_index]
        for sample_b, text_vector_b in new_vectors:
            sim_score = similarity(text_vector_a, text_vector_b)[0][1]
            sample_pair = sorted((sample_a, sample_b))
            score = sample_pair[0], sample_pair[1], sim_score
            results.add(score)
    return results

In [12]:
for data in check_plagiarism():
    print(data)

('doc1.txt', 'doc2.txt', 0.43911841058824574)
('doc1.txt', 'doc3.txt', 0.6637196184690205)
('doc2.txt', 'doc3.txt', 0.43911841058824574)
