<a href="https://colab.research.google.com/github/nabilaaryanti/Aljabar_Linear/blob/main/Aplikasi_Ruang_Vektor_untuk_Deteksi_Plagiarism.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! git clone https://github.com/nabilaaryanti/Aljabar_Linear.git

Cloning into 'Aljabar_Linear'...
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 25 (delta 6), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (25/25), done.


In [2]:
import os
from numpy import vectorize 
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [13]:
os.chdir("/content/Aljabar_Linear/Data")

In [14]:
sample_files = [doc for doc in os.listdir() if doc.endswith('.txt')]
sample_files

['doc2.txt', 'doc3.txt', 'doc1.txt']

In [15]:
open('doc1.txt').read()

'Saya tidak suka buah mangga'

In [16]:
sample_contents = [open(File).read() for File in sample_files]
sample_contents

['Saya suka makan buah mangga',
 'Saya tidak suka makan buah apapun',
 'Saya tidak suka buah mangga']

In [7]:
vectorize = lambda Text: TfidfVectorizer().fit_transform(Text).toarray()
vectorize

<function __main__.<lambda>>

In [8]:
similarity = lambda doc1, doc2: cosine_similarity([doc1, doc2])
similarity

<function __main__.<lambda>>

In [18]:
vectors = vectorize(sample_contents)
vectors

array([[0.        , 0.3978967 , 0.51236445, 0.51236445, 0.3978967 ,
        0.3978967 , 0.        ],
       [0.55873062, 0.32999531, 0.42492904, 0.        , 0.32999531,
        0.32999531, 0.42492904],
       [0.        , 0.3978967 , 0.        , 0.51236445, 0.3978967 ,
        0.3978967 , 0.51236445]])

In [19]:
s_vectors = list(zip(sample_files, vectors))
s_vectors

[('doc2.txt',
  array([0.        , 0.3978967 , 0.51236445, 0.51236445, 0.3978967 ,
         0.3978967 , 0.        ])),
 ('doc3.txt',
  array([0.55873062, 0.32999531, 0.42492904, 0.        , 0.32999531,
         0.32999531, 0.42492904])),
 ('doc1.txt',
  array([0.        , 0.3978967 , 0.        , 0.51236445, 0.3978967 ,
         0.3978967 , 0.51236445]))]

In [20]:
def check_plagiarism():
    results = set()
    global s_vectors
    for sample_a, text_vector_a in s_vectors:
        new_vectors = s_vectors.copy()
        current_index = new_vectors.index((sample_a, text_vector_a))
        del new_vectors[current_index]
        for sample_b, text_vector_b in new_vectors:
            sim_score = similarity(text_vector_a, text_vector_b)[0][1]
            sample_pair = sorted((sample_a, sample_b))
            score = sample_pair[0], sample_pair[1], sim_score
            results.add(score)
    return results

In [21]:
for data in check_plagiarism():
    print(data)

('doc1.txt', 'doc3.txt', 0.6116306633888977)
('doc1.txt', 'doc2.txt', 0.7374826745521686)
('doc2.txt', 'doc3.txt', 0.6116306633888977)
