<a href="https://colab.research.google.com/github/nabilaaryanti/Aljabar_Linear/blob/main/Invers_Matriks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Langkah 1:**

Install library NumPy pada python. Library NumPy merupakan singkatan dari Numerical Python. NumPy merupakan salah satu library Python yang berfungsi untuk proses komputasi numerik. NumPy memudahkan kita untuk operasi elementwise pada Vektor dan Matriks seperti penjumlahan, perkalian, pangkat, dan operasi lainnya.

In [1]:
import numpy as np

**Langkah 2:**

Gunakan array pada NumPy yang berfungsi untuk menyimpan data sebagai grid atau matriks. Lalu buat variabel A yang berisi matriks A 

In [5]:
A = np.array([[6, 1, 1, 3],
              [4, 0, 5, 1],
              [2, 1, 7, 6],
              [0, 1, 9, 0]])

**Langkah 3:**

Setelah mendefinisikan sebuah matriks, akan digunakan fungsi linalg.inv(A) untuk mencari invers dari matriks A. linalg merupakan fungsi pada NumPy yang digunakan untuk menyelesaikan persamaan aljabar linear

In [3]:
invers = np.linalg.inv(A)

Print invers dari matriks A

In [9]:
print("Invers Matriks A: \n", invers)

Invers Matriks A: 
 [[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]
