<a href="https://colab.research.google.com/github/nabilaaryanti/Aljabar_Linear/blob/main/Sistem_Persamaan_Linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Soal

Sebuah pabrik lensa memiliki 4 unit mesin, yaitu A,B, C dan D. Jika semua mesin bekerja, maka sebanyak 12.400 lensa dapat dihasilkan dalam waktu satu minggu. Jika hanya menggunakan mesin A, B dan C yang bekerja, maka 8.200 lensa dapat dihasilkan dalam satu minggu. Lalu, jika pabrik hanya menggunakan mesin A, C dan D, maka 9.500 lensa dapat dihasilkan dalam satu minggu. Sedangkan jika pabrik menggunakan hanya mesin A dan D, maka 5.600 lensa dapat dihasilkan setiap minggunya. Berapa banyak lensa yang dihasilkan tiap-tiap mesin dalam waktu satu minggu? Manakah mesin yang dapat menghasilkan lensa terbanyak?

In [ ]:
# Instalisasi Library yang dibutuhkan
# Untuk menyelesaikan suatu SPL membutuhkan library Numpy
import numpy as np

Selanjutnya kita gunakan funsi array pada NumPy yang berfungsi untuk menyimpan data sebagai grid atau matriks.

In [ ]:
# Defisikan 2 buah variabel untuk menampung matriks koefien dan matriks konstanta
# Variabel M berisi matriks koefisien SPL
M = np.array([(1, 1, 1, 1),  #baris 1
             (1, 1, 1, 0),  #baris 2
             (1, 0, 1, 1),  #baris 3
             (1, 0, 0, 1)]) #baris 4

In [ ]:
# Variabel N berisi matriks konstanta SPL
N = np.array([12400, 8200, 9500, 5600])

Setelah mendefinisikan kedua variabel matriks, akan digunakan sebuah fungsi untuk memecahkan persamaan aljabar linear yaitu "linalg"

In [ ]:
# fungsi linalg pada numpy berfungsi untuk membantu memecahkan persamaan aljabar linear
x = np.linalg.solve(M,N)

# Print jawaban
print("Mesin A : ", int(x[0]))
print("Mesin B : ", int(x[1]))
print("Mesin C : ", int(x[2]))
print("Mesin D : ", int(x[3]))

Mesin A :  1400
Mesin B :  2900
Mesin C :  3900
Mesin D :  4200


Mencari Determinan Matriks Menggunakan Python

In [ ]:
# Instalisasi Library yang dibutuhkan
# Untuk menyelesaikan suatu Determinan matriks dibutuhkan library Numpy
import numpy as np

In [ ]:
# Definisikan sebuah variabel untuk menampung matriks nxn
# Pada contoh ini adalah matriks dengan ordo 4x4 dan 6x6
#contoh 1 (matriks 4x4)
A = np.array([(1, 1, 1, 1),  #baris 1
             (1, 1, 1, 0),  #baris 2
             (1, 0, 1, 1),  #baris 3
             (1, 0, 0, 1)]) #baris 4

#print matriks A
print(A)

[[1 1 1 1]
 [1 1 1 0]
 [1 0 1 1]
 [1 0 0 1]]


In [ ]:
# Untuk mencari determinan, gunakan fungsi linalg.det() 
Det_A = np.linalg.det(A) #determinan dari matriks A

# print jawaban
print("Determinan matriks A adalah", int(Det_A))

Determinan matriks A adalah -1


In [ ]:
# contoh 2 (matriks 6x6)
B = np.array([(1, 2, 3, 4, 5, 2),  #baris 1
             (1, 1, 3, 0, 1, 0),   #baris 2
             (2, 0, 2, 1, 0, 4),   #baris 3
             (0, 0, 3, 1, 2, 2),   #baris 4
             (4, 0, 0, 1, 0, 0),   #baris 5
             (1, 1, 2, 2, 3, 3)])  #baris 6

#print matriks B
print(B)

[[1 2 3 4 5 2]
 [1 1 3 0 1 0]
 [2 0 2 1 0 4]
 [0 0 3 1 2 2]
 [4 0 0 1 0 0]
 [1 1 2 2 3 3]]


In [ ]:
# Untuk mencari determinan, gunakan fungsi linalg.det() 
Det_B = np.linalg.det(B) #determinan dari matriks A

# print jawaban
print("Determinan matriks A adalah", int(Det_B))

Determinan matriks A adalah 217
